window.background.image.scale=true
window.transparency=1
window.title.menu=true
window.always.top=false
window.background.image.alpha=0.8
window.image.enable=true
window.absorb=true
window.round=false
window.theme=深色