window.background.image.scale=true
window.transparency=0.8
window.title.menu=false
window.always.top=false
window.background.image.alpha=0.8
window.image.enable=true
window.absorb=true
window.round=true
window.theme=深色